<script lang="ts">
  import { onMount } from "svelte";

  export let competitionId: string;
  export let teamId: string;
  export let feedbackReleaseDate: string | null | undefined;

  let narrative = "";
  let loading = true;
  let isReleased = false;
  let error = "";

  // Reactively check if the feedback should be visible
  $: {
    if (feedbackReleaseDate) {
      const releaseTime = new Date(feedbackReleaseDate).getTime();
      const now = new Date().getTime();
      isReleased = now >= releaseTime;
    } else {
      isReleased = false;
    }
  }

  async function loadFeedback() {
    if (!isReleased) {
      loading = false;
      return;
    }

    try {
      loading = true;
      const response = await fetch(`/api/competitions/${competitionId}/submissions/${teamId}/feedback`, {
        headers: {
          'Authorization': `Bearer ${localStorage.getItem('accessToken')}`
        }
      });
      
      if (response.ok) {
        const data = await response.json();
        narrative = data.narrative || "";
      } else {
        error = "The AI is still processing your constructive narrative. Check back soon!";
      }
    } catch (err) {
      error = "Unable to reach the AI Synthesis agent.";
    } finally {
      loading = false;
    }
  }

  onMount(loadFeedback);

  function formatDate(d: string) {
    return new Date(d).toLocaleDateString('en-US', {
      weekday: 'long', month: 'long', day: 'numeric', year: 'numeric',
      hour: '2-digit', minute: '2-digit'
    });
  }
</script>

<div class="feedback-card" class:locked={!isReleased}>
  <div class="card-header">
    <div class="badge">
      <span class="sparkle">✨</span> AI Synthesis
    </div>
    <h2>Professional Critique Narrative</h2>
  </div>

  {#if loading}
    <div class="status-box">
      <div class="shimmer-line title"></div>
      <div class="shimmer-line body"></div>
      <div class="shimmer-line body"></div>
      <p>Consulting our AI Mentor...</p>
    </div>
  {:else if !isReleased}
    <div class="locked-content">
      <div class="lock-visual">
        <div class="lock-circle">🔒</div>
      </div>
      <h3>Narrative Locked</h3>
      <p>We're aggregating 5 judge perspectives to create your cohesive feedback story.</p>
      <div class="release-info">
        <span class="label">Releasing on</span>
        <span class="date">{feedbackReleaseDate ? formatDate(feedbackReleaseDate) : 'TBD'}</span>
      </div>
    </div>
  {:else if narrative}
    <div class="unlocked-content scale-in">
      <blockquote>
        <span class="quote-mark">“</span>
        <p>{narrative}</p>
      </blockquote>
      <div class="card-footer">
        Generated by CMIS AI synthesis agent based on all judge submissions.
      </div>
    </div>
  {:else}
    <div class="error-content">
      <p>{error || "No narrative found for this team yet."}</p>
    </div>
  {/if}
</div>

<style>
  .feedback-card {
    background: white;
    border-radius: 20px;
    padding: 2.5rem;
    border: 1px solid rgba(0,0,0,0.08);
    box-shadow: 0 10px 40px rgba(0,0,0,0.04);
    margin-top: 2rem;
    position: relative;
    overflow: hidden;
  }

  .feedback-card.locked {
    background: linear-gradient(145deg, #ffffff 0%, #f9f9ff 100%);
  }

  .card-header {
    display: flex;
    align-items: center;
    gap: 1.25rem;
    margin-bottom: 2rem;
  }

  .badge {
    background: #500000;
    color: white;
    padding: 0.4rem 1rem;
    border-radius: 30px;
    font-size: 0.75rem;
    font-weight: 800;
    text-transform: uppercase;
    letter-spacing: 0.1em;
    display: flex;
    align-items: center;
    gap: 0.5rem;
  }

  h2 {
    margin: 0;
    font-size: 1.35rem;
    color: #1a1a1a;
    font-weight: 700;
  }

  /* Locked State Styles */
  .locked-content {
    text-align: center;
    padding: 2rem 0;
  }

  .lock-visual {
    margin-bottom: 1.5rem;
  }

  .lock-circle {
    width: 80px;
    height: 80px;
    background: #50000010;
    border-radius: 50%;
    margin: 0 auto;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 2.5rem;
    border: 1px solid #50000020;
  }

  h3 { color: #500000; margin: 0 0 0.5rem; font-size: 1.25rem; }
  p { color: #666; font-size: 0.95rem; margin-bottom: 2rem; line-height: 1.6; }

  .release-info {
    display: inline-flex;
    flex-direction: column;
    padding: 1rem 2rem;
    background: white;
    border: 1px solid #eee;
    border-radius: 12px;
    box-shadow: 0 4px 15px rgba(0,0,0,0.03);
  }

  .release-info .label { font-size: 0.7rem; text-transform: uppercase; color: #999; font-weight: 700; margin-bottom: 0.25rem; }
  .release-info .date { color: #1a1a1a; font-weight: 600; font-size: 0.95rem; }

  /* Unlocked State Styles */
  blockquote {
    margin: 0;
    padding: 1.5rem 2.5rem;
    background: #fdfdfd;
    border-left: 5px solid #500000;
    border-radius: 8px;
    position: relative;
    font-style: italic;
  }

  .quote-mark {
    position: absolute;
    top: 0.5rem;
    left: 0.75rem;
    font-size: 4rem;
    color: #50000010;
    font-family: serif;
    line-height: 1;
  }

  blockquote p {
    color: #333;
    font-size: 1.1rem;
    line-height: 1.8;
    margin: 0;
  }

  .card-footer {
    margin-top: 2rem;
    font-size: 0.8rem;
    color: #aaa;
    text-align: right;
  }

  /* Shimmer / Loading */
  .shimmer-line {
    background: #f0f0f0;
    background-image: linear-gradient(90deg, #f0f0f0 0%, #f8f8f8 50%, #f0f0f0 100%);
    background-repeat: no-repeat;
    background-size: 200px 100%;
    animation: shimmer 1.5s infinite linear;
    border-radius: 4px;
    margin-bottom: 1rem;
  }
  .shimmer-line.title { height: 24px; width: 60%; }
  .shimmer-line.body { height: 16px; width: 100%; }

  @keyframes shimmer {
    0% { background-position: -200px 0; }
    100% { background-position: 200px 0; }
  }

  .scale-in {
    animation: scaleIn 0.5s cubic-bezier(0.165, 0.84, 0.44, 1);
  }

  @keyframes scaleIn {
    0% { opacity: 0; transform: scale(0.98); }
    100% { opacity: 1; transform: scale(1); }
  }
</style>
